### ISSUE TITLE
body txt style

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#39]
set up body font weight to 600 (better readability)

**Comment by notionparallax** [comment]
@patriktyppo 600 and bold seem to be identical. I don't think that blender supports numbered weights.

![image](https://cloud.githubusercontent.com/assets/1865196/7113319/da43f90a-e215-11e4-9265-c76ba5891037.png)

If you inspect a `p` you can toggle the weights by turning them on and off.
