### ISSUE TITLE
sub menu style

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#40]
font size 26px book. color R180 G180 B180 (also numbers 01 02 03...). Hover not underline. Marker where you are brown, no underline.

Main menu should be align with the sub menu/content
![image](https://cloud.githubusercontent.com/assets/11640099/6889215/89e2823a-d6dd-11e4-8ce0-8baf5229ffdf.png)

**Comment by patriktyppo** [comment]
Font size is not right and the weight is too big/strong now than the body text change affected on this style too. I want only body text to be stronger and everything else stay as they are. Also we are missing marker indicator (shows where you are at the moment (brown color)).

**Comment by patriktyppo** [comment]
Font size 26px

**Comment by patriktyppo** [comment]
need action

**Comment by notionparallax** [comment]
I'm going to close this. If there are specific font changes, open one issue per change
