### ISSUE TITLE
Header layout

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#44]
Here's the layout and some guides to build the header
![image](https://cloud.githubusercontent.com/assets/11640099/6890075/1632b064-d6ef-11e4-8784-1c515bf3a8ff.png)

**Comment by notionparallax** [comment]
I can't see any guides

**Comment by patriktyppo** [comment]
well gaps between top, main & subheading and content. 30px, 30px, 60px
can't u see the image?

**Comment by notionparallax** [comment]
No, I can see the image, I just couldn't see any guides.
