### ISSUE TITLE
Body Font weight

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#60]
Only body font weight should be 600. It seems that this change affected headings too (600 is too heavy for them cause they are already medium). Also some of the body txt is 600 and some 300. Example bullet points and team list is still 300.
Here's screen shot:
![image](https://cloud.githubusercontent.com/assets/11640099/7127507/b02f52c2-e288-11e4-84c3-e75c0351697b.png)

**Comment by notionparallax** [comment]
Did you see the comment about numbered weights not being meaningful? Only
regular and bold. Numbered weights will default to whatever is closest.

**Comment by patriktyppo** [comment]
No I didn't see that comment and I don't really understand what that means? Only thing what I wanted was to get only body text stronger and keep everything else how they are.

**Comment by notionparallax** [comment]
check out https://github.com/bvn-architecture/transformative/issues/39

you can just inspect some body text and toggle the weights.

It's more just for your interest. I'll interpret the intent.

**Comment by patriktyppo** [comment]
What if we set body txt "blender Medium" instead of fixing weight?

**Comment by notionparallax** [comment]
The body is medium now.

**Comment by patriktyppo** [comment]
I think it's good now. Check bullet point and team members styles also, they seem to be book still.

**Comment by patriktyppo** [comment]
Need action. Also we have too many bullet point styles, just circle please.

**Comment by notionparallax** [comment]
circle or disk? (stroked or filled)

Also, start a new issue for new things, it makes it easier to track

**Comment by patriktyppo** [comment]
filled please
