### ISSUE TITLE
link style

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#64]
There's weird orange box appearing when you click links. Also front page taglines are not links.
In front page editorial text is not fitting in.
![image](https://cloud.githubusercontent.com/assets/11640099/7171726/66b69838-e41f-11e4-801a-56c1b1b7cece.png)
![image](https://cloud.githubusercontent.com/assets/11640099/7171733/9016773e-e41f-11e4-8517-5d5aa930d46d.png)

**Comment by notionparallax** [comment]
The site isn't deploying at the moment. It'll be up again later today
hopefully.
