### ISSUE TITLE
header transparency

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#73]
Can we change header transparency to solid color? I think it will work better. R30 G30 B30 (same as bg color).

![image](https://cloud.githubusercontent.com/assets/11640099/8370640/08a40de4-1c0e-11e5-9661-a87696fde0e3.png)

**Comment by notionparallax** [comment]
try it, see what you think. Just change the 0.8 to a 1

**Comment by patriktyppo** [comment]
at the moment site is looking like this (can't test yet) :
![image](https://cloud.githubusercontent.com/assets/11640099/8370702/0394f1d2-1c0f-11e5-86f8-7a56ba6e12ad.png)

**Comment by patriktyppo** [comment]
I tested different values and I think it's best to go with solid bg with this one (1).
