### ISSUE TITLE
sub menu style change

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#80]
Sub menu style is different than layout. 
![image](https://cloud.githubusercontent.com/assets/11640099/8401377/e702b8ba-1e70-11e5-8a7d-3c4255bc47b0.png)

See layout:
![image](https://cloud.githubusercontent.com/assets/11640099/8401383/05e9c4d0-1e71-11e5-9279-8ccfde26e610.png)

**Comment by notionparallax** [comment]
Is it the centring, the line break or both that you want to change?

**Comment by patriktyppo** [comment]
We need to change the number (same font style and color all over) and the link style (underline) going thru the word. Here's sample. This is that we have simple and consistent styles thru the website.
![image](https://cloud.githubusercontent.com/assets/11640099/8402058/b36c3346-1e7a-11e5-8de6-09f98b43d2b8.png)

Don't worry about line brake. That happens automatically depending on window size.
