### ISSUE TITLE
index image numbers

### ISSUE THREAD

**Issue by patriktyppo** [bvn-architecture/transformative#99]
change circle size to 30 px and font 16px. 

Do you think all this numbering stories is necessary? Is it clearer or just making it more confusing? If you have a magazine you don't number your stories in there. We already have a hierarchy thru layout... @stelladevulder might be the right person to answer this

**Comment by notionparallax** [comment]
![image](https://cloud.githubusercontent.com/assets/1865196/8445842/bd32abfa-1fe5-11e5-9ed0-13e3c5f16b91.png)

Is that what you meant?

**Comment by patriktyppo** [comment]
No I meant index page numbers:
![image](https://cloud.githubusercontent.com/assets/11640099/8445952/0c01332c-1fe7-11e5-8d49-8d8e17c1981b.png)

I'll get back to this carousel later...
